version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /tourist-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /tourist-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /tourist-app/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "building phase..."
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/tourist-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/tourist-app:latest"
  post_build:
    commands:
      - echo "Hurray build successful!"

